im:
  server:
#    port:
    port: 7777
  route:
    server:
      ip: 127.0.0.1
      port: 9191

#kafka
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      value-serializer: com.common.kafka.serialize.MsgSerializer
    consumer:
      value-deserializer: com.common.kafka.serialize.MsgDeserializer
  #redis
  redis:
    host: 127.0.0.1
    port: 6379